ALTER TABLE `[#DB_PREFIX#]topic` ADD `url_token` VARCHAR( 32 ) NULL DEFAULT NULL;
ALTER TABLE `[#DB_PREFIX#]topic` ADD INDEX (  `url_token` );
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('welcome_message_pm', 's:187:"尊敬的{username}，您已经注册成为{sitename}的会员，请您在发表言论时，遵守当地法律法规。\n如果您有什么疑问可以联系管理员。\n\n{sitename}\n{time}";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('welcome_message_email', 's:187:"尊敬的{username}，您已经注册成为{sitename}的会员，请您在发表言论时，遵守当地法律法规。\n如果您有什么疑问可以联系管理员。\n\n{sitename}\n{time}";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('time_style', 's:1:"Y";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('reputation_log_factor', 's:1:"3";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('recommend_topics_number', 's:1:"5";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('focus_topics_list_per_page', 's:1:"5";');
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('advanced_editor_enable', 's:1:"Y";');
DELETE FROM `[#DB_PREFIX#]system_setting` WHERE `varname` = 'url_param_key';
ALTER TABLE `[#DB_PREFIX#]category` ADD `url_token` VARCHAR( 32 ) NULL DEFAULT NULL;
ALTER TABLE `[#DB_PREFIX#]category` ADD INDEX (  `url_token` );
ALTER TABLE `[#DB_PREFIX#]feature` ADD `url_token` VARCHAR( 32 ) NULL DEFAULT NULL;
ALTER TABLE `[#DB_PREFIX#]feature` ADD INDEX (  `url_token` );
INSERT INTO `[#DB_PREFIX#]system_setting` (`varname`, `value`) VALUES ('auto_question_lock_day', 's:2:"30";');
ALTER TABLE `[#DB_PREFIX#]question` ADD INDEX (  `lock` );
DELETE FROM `[#DB_PREFIX#]question_keyword` WHERE `keyword` LIKE '%了%';
DELETE FROM `[#DB_PREFIX#]question_keyword` WHERE `keyword` LIKE '%的%';
DELETE FROM `[#DB_PREFIX#]question_keyword` WHERE `keyword` LIKE '%有%';